### ISSUE TITLE
Question about the dataset converting

### ISSUE THREAD

**Issue by Griefoak** [magnumical/GCN_for_EEG#1]
Sorry to bother you! I'd like to ask something about dataset converting.
I am conducting research on EEG, and I read your github code, which is very enlightening, but it also caused some problems.
1. If only a small amount but not all of the data you provide is used, do I only need to change the size of the matrix? It would be great if you could give an example.
2. How should we cite other data? Including different data formats, different number of EEG channels and different matrix sizes?
Thank you for reading and answering, thank you.

**Comment by magnumical** [comment]
This is a great question!
first of All, researchers in EEG area use various types of formats such as .edf, .gdf, .mat etc.
So covering all of this types needs more effort and using various libraries . the purpose of sharing codes on GitHub is such a things. You can build sth and someone can develop it to be generalized! 

Answer to your questions:
1. You should change! I think that knowing the origin of these numbers can help you:
_1075200_ is size of all stacked data of 20 subjects, adjust it with your desired version. As you know, we used PhysioNet dataset which has 64 electrodes! 
_84_ is number of all trials.
_640_ is number of data points. The data is sampled at _160_ Hz, and window for motor imagery is 4 sec. so we will have _160*4_ samples.

Based on you personal data, change line 32 and 33 in _onEEGcode.py_ which determines the shape of labels.
Also for smaller dataset, it's good to revise batch size and evaluation frequency.

2. I didn't develop a automatic version! so you should fork the code and change it to meet your needs! For different data formats, you can easily search and find related libraries.
Different EEG channels: you can replace 64 with N and 63 with N-1

**Key point!**
You should change this line of code:
`params['M'] = [4]`
4 is number of FC layers, and determines the number of classes that you have

I hope that this answer will help you!
