### ISSUE TITLE
Program operation problem

### ISSUE THREAD

**Issue by Griefoak** [magnumical/GCN_for_EEG#2]
Thank you for your previous reply, you are really a respectable scholar.
I don't know if it is a problem with my computer or the processing steps. After the .csv file is generated and the onEEGcode.py program is run, an error of “ValueError: could not convert string to float” will be reported. But after I checked, I didn't find any structure other than string. How should I modify the program?
The place where the error occurred is at “onEEGcode.py”->"train_data, train_labels, test_data, test_labels= dataread(DIR)"->"dataread.py"->"train_data = np.array(train_data).astype('float32')"
thank you for your reply.

**Comment by magnumical** [comment]
Thanks you!
Please clone again, I changed some parts of the code that may act wrong in different IDEs!

In detail: I changed _02prepairdata_ to build `.npy` files which is so easier to work.

**Comment by Griefoak** [comment]
Sorry to disturb you again, but the problem of "ValueError: could not convert string to float:" still exists, this time it appears in onEEGcode.py, line 45. The code changed on GitHub lacks the address of DIR, and test_labels becomes 107519 instead of 107520.

**Comment by magnumical** [comment]
No problem! This is just fixed! There is no need to _DIR_  just put the results of _02_ into `files` folder.
FYI, it _onEEGcode.py_ need adjacency matrix and four` .npy` file.

**Comment by Griefoak** [comment]
Thank you for your patient answer, but the problem does exist. I uploaded two screenshots of the problems that occurred when the program was running (I used pycharm to run the program). Picture 1 is a problem of matrix reshape, and picture 2 is a problem of str to float.
Remarks: Your answer has benefited me a lot, and your character is respected. There is a poem in the East: "As long as one has a true friend, he is close even when far away." If it conforms to the customs of your country, I want to say that I want to be friends with you.
picture：
![1](https://user-images.githubusercontent.com/56536044/92421876-67b87700-f1ad-11ea-8ce7-3813334f37a2.png)
![2](https://user-images.githubusercontent.com/56536044/92421877-69823a80-f1ad-11ea-912a-844270227229.png)

**Comment by magnumical** [comment]
Yeah! I forgot to fix this issue! 
Thank you! and I'm sorry about this issues that you faced. This was related to your previous problem with working on CSV files. I changed the format for Adjacency Matrix too. I checked it and it works!

Just dont forget to copy .npy files from second step to `files `folder
