### ISSUE TITLE
data-labels-question 

### ISSUE THREAD

**Issue by hningy** [magnumical/GCN_for_EEG#3]
Hello, sorry to disturb you, when I saw how to read the data in your GCN_for_EEG, it is all the fourth category, the training accuracy is 0%, that is, in the first edfread.py, the labels seem to be fully assigned It is [0,0,0,1], I hope you can answer my question. Is it my problem? Is your result normal? Thank you

**Comment by magnumical** [comment]
Hi! no problem!
Which environment do you use?! you are suggested to run this part on` python 2.7`
My results are normal, I also shared an image of my resulted _TensorBoard_ in `readme.md` file of this project.

**Comment by hningy** [comment]
> Hi! no problem!
> Which environment do you use?! you are suggested to run this part on` python 2.7`
> My results are normal, I also shared an image of my resulted _TensorBoard_ in `readme.md` file of this project.



> Hi! no problem!
> Which environment do you use?! you are suggested to run this part on` python 2.7`
> My results are normal, I also shared an image of my resulted _TensorBoard_ in `readme.md` file of this project.

OK，thanks,I have used the python3.5 ,I  changed it to python2.7  ,now the problom is solved

**Comment by jzmclover** [comment]
> Hello, sorry to disturb you, when I saw how to read the data in your GCN_for_EEG, it is all the fourth category, the training accuracy is 0%, that is, in the first edfread.py, the labels seem to be fully assigned It is [0,0,0,1], I hope you can answer my question. Is it my problem? Is your result normal? Thank you

Hello, may I ask what are the correct labels on your computer? I got the labels like this:
0	1	0	0
1	0	0	0
1	0	0	0
0	1	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
0	1	0	0
1	0	0	0
1	0	0	0
0	1	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
1	0	0	0
0	1	0	0
0	1	0	0
1	0	0	0
1	0	0	0
0	1	0	0
0	1	0	0
1	0	0	0
0	1	0	0
1	0	0	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	1	0
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1
0	0	0	1

The labels come from the first subject and I don't know whether the labels are correct, the latter half of the labels seems wrong. I use python 2.7 environment, too.
