### ISSUE TITLE
EDF documents can't be opened

### ISSUE THREAD

**Issue by XieTianLi** [magnumical/GCN_for_EEG#5]
I have download the efd documents by using downloaddata.py. However, when I use the edfread.py to excate the edf, an error has occurred.
    return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)), \

IndexError: list index out of range

when I debug it, I found that the edf can't be opened.

Do you know how to debug it? Or would you mind sharing the complied .mat documents. Thank you for your helping and apologies for disturbing you!

**Comment by magnumical** [comment]
Hi,
you just need to place all the` .edf `files in _`01loadData`_ folder. It's better to download all the files from physionet. 
you'll have s001 to s109
Then on the search bar search: `*.edf`
It will show you all the .edf files. copy them all to that folder I mentioned and run `edfread.py`. make sure you are using Py 2.7
The compiled .mat files are about 528mb. I will try send them as soon as you couldn't troubleshoot.

**Comment by XieTianLi** [comment]
Thank you so much for your reply and your outstanding work! And in what form will the .mat file be sent to me?

**Comment by XieTianLi** [comment]
Thank you so much for your reply and your outstanding work! And in what form will you share the .mat file?

**Comment by XieTianLi** [comment]
Thank you for your response and outstanding work! I did run it in py2.7. And my friend had the same problem, he downloaded all the files and ran them in py2.7 environment.
I got this error while debugging.
 [info] initializing!
 [info] Start to save the Files!
--Call--
TypeError: int() argument must be a string, a bytes-like object or a number, not 'range'
--Call--
--Call--
OSError: the file is not EDF(+) or BDF(+) compliant (Prefilter)

Maybe it's an EDF problem.

**Comment by magnumical** [comment]
I just ran the code flawless with ` pyedflib.__version__= '0.1.17'`.
I will try to zip and upload .mat on google drive as soon as possible!

**Comment by magnumical** [comment]
.mat files are here: 
[GOOGLE DRIVE](https://drive.google.com/file/d/1ZOm_jGuhbOFOjh-QtC37mGyS4zR0aUik/view?usp=sharing)

**Comment by XieTianLi** [comment]
Thank you very much for your help!
