### ISSUE TITLE
code 

### ISSUE THREAD

**Issue by shenjianaixuexi** [magnumical/GCN_for_EEG#6]
Hello friend,
 I have got this problem.
(Traceback (most recent call last):
  File "edfread.py", line 225, in <module>
    X, Y = load_raw_data(electrodes=electrodes, subject=subject, num_classes=nclasses)
  File "edfread.py", line 169, in load_raw_data
    return np.array(trials, dtype=np.float64).reshape((len(trials),) + trials[0].shape + (1,)),  np.array(labels, dtype=np.float64)
IndexError: list index out of range.)
 Can you give me some advice Thanks anyway!

**Comment by magnumical** [comment]
hi
check out this issue:
[https://github.com/magnumical/GCN_for_EEG/issues/5](https://github.com/magnumical/GCN_for_EEG/issues/5)
